### PR TITLE
ListenDirective

### PR DESCRIPTION
**Pull request by pulgamecanica**
Don't Forget to increment here:
https://github.com/BrenoMachado123/webserver/blob/9cc19293d889582aec7447433880e5df6f57af91/srcs/Config.cpp#L185
I would replace this line with something like this:
`for (; it != content.end(); ++it)`
***
[listen valid examples](https://nginx.org/en/docs/http/ngx_http_core_module.html#listen)
Screen Shot 2022-05-28 at 23 52 51
***
Cheers & GL!

### CODE REVIEW

**Comment by pulgamecanica** [comment]
_name should be const.
https://github.com/BrenoMachado123/webserver/blob/d99bca2d95f3ce958fa58bd22a36958ee928354d/includes/Config.hpp#L96
You should check for repeated codes as well 😄 
***
Don't reference int.
https://github.com/BrenoMachado123/webserver/blob/d99bca2d95f3ce958fa58bd22a36958ee928354d/includes/Config.hpp#L124
should be 
`int getPort() const;`

**Comment by pulgamecanica** [comment]
All directives must check if str is empty....

**Comment by psleziak42** [comment]
Why to not 
const int &getPort() const; but int getPort() const; ??

Isnt it like we "always" return reference from getters?

**Comment by psleziak42** [comment]
> 

what do you mean code repetitive?

**Comment by psleziak42** [comment]
added content.empty() to listen and error

**Comment by pulgamecanica** [comment]
#### Simplicity
***

https://github.com/BrenoMachado123/webserver/blob/abbc0821e6ff516fe7adbd998a184a89d347c9d4/srcs/Config.cpp#L186

In this line, you call a helper function to determine if a string has at least one "separator/isspace".
It would be better if you could find a more c++ish way to do it.

You can use the function find instead of using a helper function.
If find == end then it didn't find any spaces...

**Pull request merged**
